{"uuid": "6d1deba8-0498-4025-b9bd-0fd5bac36853", "children": ["2e54b8fd-5ed7-4cc6-b913-2c9bd52b2f65", "4ae4f1fe-a16c-4737-8d89-b1bf7493e482", "04adef65-fcbc-43f6-8e8a-bbf11b1405f1", "d02bbd31-2efc-4a83-8f34-aadba56cbdf1"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist\nStacktrace:\n0   chromedriver                        0x000000010b1aa2c8 chromedriver + 4752072\n1   chromedriver                        0x000000010b12a463 chromedriver + 4228195\n2   chromedriver                        0x000000010ad8db18 chromedriver + 441112\n3   chromedriver                        0x000000010adb907f chromedriver + 618623\n4   chromedriver                        0x000000010adb4ddb chromedriver + 601563\n5   chromedriver                        0x000000010adb0e3c chromedriver + 585276\n6   chromedriver                        0x000000010adf3c43 chromedriver + 859203\n7   chromedriver                        0x000000010adf374f chromedriver + 857935\n8   chromedriver                        0x000000010adebb33 chromedriver + 826163\n9   chromedriver                        0x000000010adbc9fd chromedriver + 633341\n10  chromedriver                        0x000000010adbe051 chromedriver + 639057\n11  chromedriver                        0x000000010b17730e chromedriver + 4543246\n12  chromedriver                        0x000000010b17ba88 chromedriver + 4561544\n13  chromedriver                        0x000000010b1836df chromedriver + 4593375\n14  chromedriver                        0x000000010b17c8fa chromedriver + 4565242\n15  chromedriver                        0x000000010b1522cf chromedriver + 4391631\n16  chromedriver                        0x000000010b19b5b8 chromedriver + 4691384\n17  chromedriver                        0x000000010b19b739 chromedriver + 4691769\n18  chromedriver                        0x000000010b1b181e chromedriver + 4782110\n19  libsystem_pthread.dylib             0x00007ff81b2424e1 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81b23df6b thread_start + 15\n\n", "trace": "  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/testcase/conftest.py\", line 22, in driver\n    get_driver = ChromeBrowser().browser\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/util/browser.py\", line 97, in browser\n    chrome = self._browser(service=self.service, options=self.options)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 81, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 106, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668559552424, "stop": 1668559635490}], "start": 1668559552424, "stop": 1668559636446}