{"uuid": "33173131-d470-461f-98f3-4e9551a90461", "children": ["b98e12ef-d52d-4d59-ab71-c193c0486549", "c584fd95-32d9-4cc5-909f-ceae9d67348c", "4d70c170-28fe-42cf-93ac-8c3ba3e3e824", "298803ea-282c-4458-8445-bbac7089724d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\nStacktrace:\n0   chromedriver                        0x0000000103e9e2c8 chromedriver + 4752072\n1   chromedriver                        0x0000000103e1e463 chromedriver + 4228195\n2   chromedriver                        0x0000000103a8198a chromedriver + 440714\n3   chromedriver                        0x0000000103a6f874 chromedriver + 366708\n4   chromedriver                        0x0000000103aad896 chromedriver + 620694\n5   chromedriver                        0x0000000103aa9046 chromedriver + 602182\n6   chromedriver                        0x0000000103aa4e3c chromedriver + 585276\n7   chromedriver                        0x0000000103ae7c43 chromedriver + 859203\n8   chromedriver                        0x0000000103ae774f chromedriver + 857935\n9   chromedriver                        0x0000000103adfb33 chromedriver + 826163\n10  chromedriver                        0x0000000103ab09fd chromedriver + 633341\n11  chromedriver                        0x0000000103ab2051 chromedriver + 639057\n12  chromedriver                        0x0000000103e6b30e chromedriver + 4543246\n13  chromedriver                        0x0000000103e6fa88 chromedriver + 4561544\n14  chromedriver                        0x0000000103e776df chromedriver + 4593375\n15  chromedriver                        0x0000000103e708fa chromedriver + 4565242\n16  chromedriver                        0x0000000103e462cf chromedriver + 4391631\n17  chromedriver                        0x0000000103e8f5b8 chromedriver + 4691384\n18  chromedriver                        0x0000000103e8f739 chromedriver + 4691769\n19  chromedriver                        0x0000000103ea581e chromedriver + 4782110\n20  libsystem_pthread.dylib             0x00007ff81ccb94e1 _pthread_start + 125\n21  libsystem_pthread.dylib             0x00007ff81ccb4f6b thread_start + 15\n\n", "trace": "  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/testcase/conftest.py\", line 22, in driver\n    get_driver = ChromeBrowser().browser\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/util/browser.py\", line 97, in browser\n    chrome = self._browser(service=self.service, options=self.options)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 81, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 106, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668550178545, "stop": 1668550260731}], "start": 1668550178545, "stop": 1668550261591}