{"uuid": "6fb2d612-73cd-44ae-b595-8c5a7bbecf5c", "children": ["03afdb8a-86c0-4c2f-b666-bc604a6145eb", "d8c3cdfc-c814-4b08-87f2-7edab51ee373", "dc9c5432-4d1d-4f12-88e3-e3f8137a237f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\nStacktrace:\n0   chromedriver                        0x000000010468b2c8 chromedriver + 4752072\n1   chromedriver                        0x000000010460b463 chromedriver + 4228195\n2   chromedriver                        0x000000010426e98a chromedriver + 440714\n3   chromedriver                        0x000000010425c874 chromedriver + 366708\n4   chromedriver                        0x000000010429a896 chromedriver + 620694\n5   chromedriver                        0x0000000104296046 chromedriver + 602182\n6   chromedriver                        0x0000000104291e3c chromedriver + 585276\n7   chromedriver                        0x00000001042d4c43 chromedriver + 859203\n8   chromedriver                        0x00000001042d474f chromedriver + 857935\n9   chromedriver                        0x00000001042ccb33 chromedriver + 826163\n10  chromedriver                        0x000000010429d9fd chromedriver + 633341\n11  chromedriver                        0x000000010429f051 chromedriver + 639057\n12  chromedriver                        0x000000010465830e chromedriver + 4543246\n13  chromedriver                        0x000000010465ca88 chromedriver + 4561544\n14  chromedriver                        0x00000001046646df chromedriver + 4593375\n15  chromedriver                        0x000000010465d8fa chromedriver + 4565242\n16  chromedriver                        0x00000001046332cf chromedriver + 4391631\n17  chromedriver                        0x000000010467c5b8 chromedriver + 4691384\n18  chromedriver                        0x000000010467c739 chromedriver + 4691769\n19  chromedriver                        0x000000010469281e chromedriver + 4782110\n20  libsystem_pthread.dylib             0x00007ff81ccb94e1 _pthread_start + 125\n21  libsystem_pthread.dylib             0x00007ff81ccb4f6b thread_start + 15\n\n", "trace": "  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/testcase/conftest.py\", line 22, in driver\n    get_driver = ChromeBrowser().browser\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/util/browser.py\", line 97, in browser\n    chrome = self._browser(service=self.service, options=self.options)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 81, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 106, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668550178659, "stop": 1668550260856}], "start": 1668550178659, "stop": 1668550261406}