{"uuid": "77784081-5247-48fa-adc3-4a756845245a", "children": ["11ff7113-4c2a-46bb-9fa2-8524d73d16bb", "4c434856-5abf-4bbf-a66d-851043ed2b00", "1dc1bc48-995c-4319-8004-15c6d57bf93e", "d77fea93-133b-4278-83aa-cf69235b8a0a"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\nStacktrace:\n0   chromedriver                        0x0000000105d352c8 chromedriver + 4752072\n1   chromedriver                        0x0000000105cb5463 chromedriver + 4228195\n2   chromedriver                        0x000000010591898a chromedriver + 440714\n3   chromedriver                        0x0000000105906874 chromedriver + 366708\n4   chromedriver                        0x0000000105944896 chromedriver + 620694\n5   chromedriver                        0x0000000105940046 chromedriver + 602182\n6   chromedriver                        0x000000010593be3c chromedriver + 585276\n7   chromedriver                        0x000000010597ec43 chromedriver + 859203\n8   chromedriver                        0x000000010597e74f chromedriver + 857935\n9   chromedriver                        0x0000000105976b33 chromedriver + 826163\n10  chromedriver                        0x00000001059479fd chromedriver + 633341\n11  chromedriver                        0x0000000105949051 chromedriver + 639057\n12  chromedriver                        0x0000000105d0230e chromedriver + 4543246\n13  chromedriver                        0x0000000105d06a88 chromedriver + 4561544\n14  chromedriver                        0x0000000105d0e6df chromedriver + 4593375\n15  chromedriver                        0x0000000105d078fa chromedriver + 4565242\n16  chromedriver                        0x0000000105cdd2cf chromedriver + 4391631\n17  chromedriver                        0x0000000105d265b8 chromedriver + 4691384\n18  chromedriver                        0x0000000105d26739 chromedriver + 4691769\n19  chromedriver                        0x0000000105d3c81e chromedriver + 4782110\n20  libsystem_pthread.dylib             0x00007ff81ccb94e1 _pthread_start + 125\n21  libsystem_pthread.dylib             0x00007ff81ccb4f6b thread_start + 15\n\n", "trace": "  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/_pytest/fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/testcase/conftest.py\", line 22, in driver\n    get_driver = ChromeBrowser().browser\n  File \"/Users/runner/work/sauce_webtest/sauce_webtest/util/browser.py\", line 97, in browser\n    chrome = self._browser(service=self.service, options=self.options)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 81, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 106, in __init__\n    super().__init__(\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 288, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 381, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/runner/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668550178543, "stop": 1668550260731}], "start": 1668550178543, "stop": 1668550261476}